from datetime import datetime,time
from app import db


class Event(db.Model):
    event_name = db.Column(db.String(20), nullable=False, primary_key=True)
    committee = db.Column(db.String(20), nullable=False)
    fest=  db.Column(db.String(20), nullable=False)
    contact_person = db.Column(db.String(20), nullable=True)
    description = db.Column(db.String(200), nullable=False)
    date_added = db.Column(db.DateTime, default=datetime.utcnow) #autogenerated
    event_datetime = db.Column(db.DateTime, nullable=False)
    ticket_price = db.Column(db.Integer, nullable=False) 
    venue = db.Column(db.String(100), nullable=False)
    phone_number = db.Column(db.Integer, nullable=False)
    image_file = db.Column(db.String(120), nullable=False)


    def get_id(self):
        return self.event_id